# Site settings
title: รัฐพงศ์ วรชาติอุดมพงศ์
email: maggotgluon@gmail.com
description: >
  อาจารย์ และนักออกแบบอิสระจากเมืองหัวหิน รับงานออกแบบทุกชนิด ตั้งแต่สื่อสิงพิมพ์ สื่อดิจิตอลไปจนถึงเว็บไซต์ และมัลติมีเดีย พร้อมที่จะแบ่งปันความรู้และรับใช้ท่านเสมอ
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maggotgluon.github.io" # the base hostname & protocol for your site
github_username:  maggotgluon
header_description: อาจารย์, นักออกแบบอิสระ, โปรแกรมเมอร์ และอื่นๆ...
blog_author_description: >
  อาจารย์ และนักออกแบบอิสระจากเมืองหัวหิน
  รับงานออกแบบทุกชนิด ตั้งแต่สื่อสิงพิมพ์ สื่อดิจิตอล
  ไปจนถึงเว็บไซต์ และมัลติมีเดีย พร้อมที่จะแบ่งปันความรู้
  และรับใช้ท่านเสมอ
# Build settings
markdown: kramdown

exclude: ['README.md']

gems: [jekyll-paginate]
paginate: 2
paginate_path: "/blog/page/:num/"

permalink: /blog/:year/:month/:title/index.html

related_project_keys: ["category", "technology"]
