# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: รัฐพงศ์ วรชาติอุดมพงศ์
email: maggotgluon@gmail.com
description: >
  อาจารย์และนักออกแบบอิสระจากเมืองหัวหิน
header_description: อาจารย์, นักออกแบบอิสระ, โปรแกรมเมอร์ และอื่นๆ...
blog_author_description: >
  อาจารย์และนักออกแบบอิสระจากเมืองหัวหิน

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maggotgluon.github.io" # the base hostname & protocol for your site
twitter_username: maggotgluon
github_username:  maggotgluon

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page/:num/"

related_project_keys: ["category", "technology"]
